apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-test # 생성할 EKS 클러스터명
  region: ${AWS_REGION} # 클러스터를 생성할 리젼
  version: "1.21"

vpc:
  id: "" # 기존에 있는 연결할 VPC id
  cidr: "192.168.0.0/22" # 클러스터에서 사용할 VPC의 CIDR
  subnets:
    private:
      test-sn1:
        id: ""
    public:
      test-sn2:
        id: ""

managedNodeGroups:
  - name: ng-1 # 클러스터의 노드 그룹명
    instanceType: m5.large # 클러스터 워커 노드의 인스턴스 타입
    desiredCapacity: 3 # 클러스터 워커 노드의 갯수
    volumeSize: 10  # 클러스터 워커 노드의 EBS 용량 (단위: GiB)
    privateNetworking: false # subnet이 프라이빗만 제공 되었을 경우 true
    ssh:
      enableSsm: true
    iam:
      withAddonPolicies:
        imageBuilder: true # AWS ECR에 대한 권한 추가
        # albIngress: true  # albIngress에 대한 권한 추가
        cloudWatch: true # cloudWatch에 대한 권한 추가
        autoScaler: true # auto scaling에 대한 권한 추가

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]